version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: my-map-frontend-dev
    command: npm run dev -- --host
    ports:
      - "8888:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=/api/places
      - VITE_TILE_SERVER_URL=/api/tiles
      - KEYCLOAK_URL=http://localhost:8081
    restart: always
